apiVersion: v1
kind: ConfigMap
metadata:
  name: torchani-config
  namespace: torchani
data:
  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_MODEL_TTL: "300"  # 5 minutes
  REDIS_RESULT_TTL: "3600"  # 1 hour
  
  # Celery Configuration
  CELERY_BROKER_URL: "redis://redis:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis:6379/2"
  CELERY_TASK_TIME_LIMIT: "600"  # 10 minutes
  CELERY_TASK_SOFT_TIME_LIMIT: "540"  # 9 minutes
  
  # GPU Configuration
  GPU_DEVICE: "cuda:0"
  GPU_MEMORY_LIMIT: "0.8"
  GPU_MEMORY_THRESHOLD: "0.7"
  
  # Model Configuration
  MODEL_MAX_LOADED: "2"
  MODEL_CACHE_DIR: "/models"
  
  # Performance Configuration
  MAX_BATCH_SIZE: "32"
  MAX_ATOMS: "500"
  REQUEST_TIMEOUT: "60"
  WORKER_THREADS: "4"
  
  # API Configuration
  API_PREFIX: "/api/v1"
  CORS_ORIGINS: '["http://localhost:3000", "https://cheminfuse.com"]'
  
  # Monitoring
  PROMETHEUS_ENABLED: "true"
  PROMETHEUS_PORT: "9090"